const content = {
  header: "A few companies I've worked with",
  jobs: [
    {
      role: 'Head of Product, Co-Founder',
      company: 'Fluxforms',
      description: 'AI-based forms analytics tool',
      points: [
        'Designed and developed an AI-based forms analytics app within 33 days.',
        'Scaled to 5000+ users in 2 months.',
        'Migrated to serverless architecture and optimized tech costs by 95%.',
        'Led VC and Angel investor pitches and landed an initial seed round of $150K.',
        'Managed a remote team of 4 engineers.',
      ],
      skills: ['Serverless', 'NextJS', 'Product Research', 'People Management'],
      linkTo: 'https://fluxforms.xyz',
    },
    {
      role: 'Head of Engineering, Co-Founder',
      company: 'Parentheses Labs, Inc.',
      description: 'Software consultancy',
      points: [
        'Co-founded a software consultancy and scaled to a remote team of 4 designers and 8 engineers within 8 months.',
        'Successfully built 10+ software products for clients in the U.S. and U.K.',
        'Scaled net revenue by 1.5x within our first year in operation.',
        'Led sales prospecting efforts and business development calls.',
      ],
      skills: ['Sales', 'People Management', 'Solutions Architecture'],
      linkTo: 'https://www.linkedin.com/company/parentheses-labs',
    },
    {
      role: 'Head of Engineering, Co-Founder',
      company: 'Blip Chat',
      description: 'AI-Powered virtual assistant for customer support',
      points: [
        'Used GPT 4 and vector embeddings to build a chat-based support assistant within 9 days.',
        'Successfully tested the beta version with a closed group of 4 large-scale companies, reducing workloads by up to 80% for customer support teams.',
        'Built the entire infrastructure on AWS serverless using SAM, effectively keeping costs as low as $10/mo.',
      ],
      skills: ['OpenAI', 'Serverless', 'NextJS', 'Artificial Intelligence'],
      linkTo: 'https://www.linkedin.com/company/parentheses-labs',
    },
    {
      role: 'Full-Stack Engineering Lead',
      company: 'Cyberrwanda',
      description: 'A digital platform for sex education',
      points: [
        'Drastically reduced cloud infrastructure costs from $500/m to just $5/m by migrating to a serverless setup.',
        'Migrated from a legacy codebase to a more efficient NextJS system within 2 months.',
        "Implemented USSD in 10 days for the app's eCommerce page.",
        'Optimized app experiences by moving to the latest React Native version, leading to a 3x faster experience for end users.',
        'Implemented a pub-sub architecture to help with async tasks and reduce wait time for app users.',
        'Contributed to a study on Sustainable and Scalable Features in Digital Health by the University of San Francisco.',
      ],
      skills: ['Serverless', 'React Native', 'Cloud Migration', 'AWS'],
      linkTo: 'https://www.cyberrwanda.org',
    },
    {
      role: 'Solutions Architect & Engineering Lead',
      company: 'Conwaste',
      description: 'A NYC 311 service for San Juan, Puerto Rico',
      points: [
        'Developed and managed 2 mobile apps and dashboards for the U.S. government and stakeholders.',
        'Developed the entire infrastructure using infrastructure as code.',
        'Built CI/CD pipelines to help ensure smooth delivery for releases.',
        'Led a remote team of 6 engineers.',
        'Liaised between the stakeholders, QA team, clients, and officials.',
      ],
      skills: ['Firebase', 'Serverless', 'NextJS', 'React Native'],
      linkTo: 'https://www.conwastepr.com/en',
    },
    {
      role: 'Engineering Consultant',
      company: 'Thena',
      description: 'A customer engagement platform for Slack',
      points: [
        'Built the MVP that led to a $2M funding round.',
        'Built and optimized a cost-efficient cloud infrastructure for scale.',
        'Set code and infra standards for the team to build faster.',
        'Cleaned up the backend pipeline to ensure snappy responses based on user feedback.',
        'Implemented a pub-sub architecture to aid async tasks and reduce wait time.',
      ],
      skills: ['NextJS', 'Serverless', 'Slack Integration', 'AWS'],
      linkTo: 'https://www.thena.ai',
    },
    {
      role: 'Engineering Consultant',
      company: 'Taloflow (YCombinator)',
      description: 'Cloud vendor evaluation tool',
      points: [
        'Built a collaborative notion like editor for cloud cost estimations using NextJS and Slate.',
        'Through research and feedback, optimized the interface leading to a 2x increase in editor performance.',
        'Managed a team of 3 engineers remotely.',
      ],
      skills: ['NextJS', 'Live Collaboration App', 'Remote'],
      linkTo: 'https://www.taloflow.ai',
    },
    {
      role: 'Solutions Architect Team Lead',
      company: 'Archimydes',
      description: 'SF-based software consultancy',
      points: [
        'Worked as a solution architect for multiple projects handling infrastructure.',
        'Worked as an engineering lead doing code reviews, customer onboarding, and client requirement checks.',
        'Built internal app templates for scalability, security, and performance.',
      ],
      skills: ['React', 'React Native', 'NodeJS', 'Firebase', 'AWS'],
      linkTo: 'https://archimydes.dev',
    },
    {
      role: 'Senior Software Engineer',
      company: 'QuantLegal Tech',
      description: 'VC facilitator application',
      points: [
        'Worked with the frontend team to build the admin apps and dashboards.',
        'Migrated a legacy create-react-app JavaScript codebase to a NextJS Typescript app.',
        'Built server-side rendered dashboards for the app.',
        'Built a scalable and extensible design system.',
      ],
      skills: ['NextJS', 'TypeScript Migration', 'Serverless'],
      linkTo: 'https://quantlegaltech.com',
    },
  ],
};

export default content;
